/**
 * Images should be stored in the `App/Images` directory and referenced using variables defined here.
 */

export default {
  	LineMenu: require('App/Assets/Images/line-menu.png'),
    Image01: require('App/Assets/Images/image01.png'),
    Pre_login_Pic: require('App/Assets/Images/Pre_login_Pic.jpg'),
    Image02: require('App/Assets/Images/image02.png'),
    Image03: require('App/Assets/Images/image03.png'),
    Image04: require('App/Assets/Images/image04.png'),
    Image05: require('App/Assets/Images/image05.png'),
    Image06: require('App/Assets/Images/image06.png'),
    Image07: require('App/Assets/Images/image07.png'),
    Image08: require('App/Assets/Images/image08.png'),
    Image09: require('App/Assets/Images/image09.png'),
    Image10: require('App/Assets/Images/image10.png'),
    Image11: require('App/Assets/Images/image11.png'),
    Image12: require('App/Assets/Images/image12.png'),
    Image13: require('App/Assets/Images/image13.png'),
    Image14: require('App/Assets/Images/image14.png'),
    Image15: require('App/Assets/Images/image15.png'),
    Image16: require('App/Assets/Images/image16.png'),
    Image17: require('App/Assets/Images/image17.png'),
    Image18: require('App/Assets/Images/image18.png'),
    Image19: require('App/Assets/Images/image19.png'),
    Image20: require('App/Assets/Images/Image20.png'),
    Image21: require('App/Assets/Images/image21.png'),
    Image22: require('App/Assets/Images/image22.png'),
    Image23: require('App/Assets/Images/image23.png'),
    Image24: require('App/Assets/Images/image24.png'),
    Image25: require('App/Assets/Images/image25.png'),
    Image26: require('App/Assets/Images/image26.png'),
    Image27: require('App/Assets/Images/image27.png'),
    Image28: require('App/Assets/Images/image28.png'),
    Image29: require('App/Assets/Images/image29.png'),
    Image30: require('App/Assets/Images/add-friend.png'),
    Image31: require('App/Assets/Images/diamond_profile.png'),
    Image32: require('App/Assets/Images/load.png'),

    GoodEtiquette: require('App/Assets/Images/food.png'),
    NiceProfile: require('App/Assets/Images/man.png'),
    TrueToProfile: require('App/Assets/Images/positiveVote.png'),
    WellMannered: require('App/Assets/Images/suit.png'),
    BubblyPersonality: require('App/Assets/Images/sun.png'),
    Intellectual: require('App/Assets/Images/page1.png'),
    Eloquent: require('App/Assets/Images/talk1.png'),
    GreatSenseHumor: require('App/Assets/Images/emoji.png'),
    GreatStyle: require('App/Assets/Images/man1.png'),
    Gentlemanly: require('App/Assets/Images/man2.png'),
    Energetic: require('App/Assets/Images/power.png'),
    Thoughtful: require('App/Assets/Images/brainstorm.png'),
    BetterThanProfile: require('App/Assets/Images/group133.png'),
    Confident: require('App/Assets/Images/success1.png'),
    GoodListener: require('App/Assets/Images/ear.png'),
    Athletic: require('App/Assets/Images/runningShoe.png'),




    Man_Selected: require('App/Assets/Images/man_selected.png'),
    Man_Normal: require('App/Assets/Images/man_normal.png'),
    Woman_Selected: require('App/Assets/Images/woman_selected.png'),
    Woman_Normal: require('App/Assets/Images/woman_normal.png'),

    Compass: require('App/Assets/Images/compass.png'),
    CompassBlue: require('App/Assets/Images/compass_blue.png'),
    Matchmaker: require('App/Assets/Images/matchmaker.png'),
    MatchmakerBlue: require('App/Assets/Images/matchmaker_blue.png'),
    Message: require('App/Assets/Images/message.png'),
    MessageBlue: require('App/Assets/Images/message_blue.png'),
    Store: require('App/Assets/Images/store.png'),
    StoreBlue: require('App/Assets/Images/store_blue.png'),
    Profile: require('App/Assets/Images/profile.png'),
    ProfileBlue: require('App/Assets/Images/profile_blue.png'),
    BoyfriendBlue: require('App/Assets/Images/boyfriend_blue.png'),
    WomanBlue: require('App/Assets/Images/woman_blue.png'),
    HangoutLogoBlue: require('App/Assets/Images/hangouts-logo_blue.png'),
    RewardBlue: require('App/Assets/Images/reward_blue.png'),
    Thumb: require('App/Assets/Images/thumb.png'),
    CreditCard: require('App/Assets/Images/creditcard.png'),
    ic_date_coach: require('App/Assets/Images/ic_date_coach.png'),
    Diamond: require('App/Assets/Images/diamond.png'),
    Gift: require('App/Assets/Images/gift.png'),
    Launch: require('App/Assets/Images/launch.png'),
    TinyStarBlue: require('App/Assets/Images/tinyStarBlue.png'),
    DiamondBlue: require('App/Assets/Images/diamond_blue.png'),

    BusinessAndFinance: require('App/Assets/Images/business-and-finance.png'),
    Money: require('App/Assets/Images/money.png'),
    MoneyBag: require('App/Assets/Images/money-bag.png'),
    XMLID22: require('App/Assets/Images/XMLID_22_.png'),
    MatchLabel:require('App/Assets/Images/match_label.png'),

    MapShot: require('App/Assets/Images/mapShot.png'),
    Stars: require('App/Assets/Images/stars.png'),
    RocketBoost: require('App/Assets/Images/rocket_boost.png'),
    DollarCoinStack: require('App/Assets/Images/dollar-coin-stack.png'),

    Hanger:require('App/Assets/Images/hanger.png'),
    Rating:require('App/Assets/Images/rating.png'),
    Search:require('App/Assets/Images/Search.png'),

    Pin:require('App/Assets/Images/pin.png'),
    LogoWhiteLabel:require('App/Assets/Images/logo_white.png'),
    BluePen:require('App/Assets/Images/pen.png'),
    MilaIcon2:require('App/Assets/Images/mila2.png'),
    GiftMatch:require('App/Assets/Images/gift_match.png'),

    // calendarGif: require('App/Assets/Images/calendar.gif'),
    clockGif: require('App/Assets/Images/clock.gif'),

    heart_eyes:require('App/Assets/Images/heart_eyes.png'),
    good:require('App/Assets/Images/good.png'),
    calendar:require('App/Assets/Images/calendar.png'),
    alarm_clock:require('App/Assets/Images/alarm-clock.png'),
    Group_68:require('App/Assets/Images/Group_68.png'),
    delete:require('App/Assets/Images/delete.png'),

    image1_tutorial: require('App/Assets/Images/image1_tutorial.png'),
    image2_tutorial: require('App/Assets/Images/image2_tutorial.png'),
    image3_tutorial: require('App/Assets/Images/image3_tutorial.png'),
    image4_tutorial: require('App/Assets/Images/image4_tutorial.png'),
    image5_tutorial: require('App/Assets/Images/image5_tutorial.png'),

    navigation: require('App/Assets/Images/navigation.png'),
    nodiscover_back: require('App/Assets/Images/nodiscover_back.png'),
    heart: require('App/Assets/Images/heart.png'),
    heart1: require('App/Assets/Images/heart1.png'),

    ic_facebook: require('App/Assets/Images/facebook.png'),
    ic_instagram: require('App/Assets/Images/instagram.png'),
    ic_linkedin: require('App/Assets/Images/linkedin.png'),
    ic_face: require('App/Assets/Images/face.png'),

    ic_smiling: require('App/Assets/Images/smiling.png'),
    ic_milahearts: require('App/Assets/Images/milahearts.png'),
    ic_likepic: require('App/Assets/Images/like_pic.png'),
    ic_passpic: require('App/Assets/Images/pass_pic.png'),

    ic_vip_pass: require('App/Assets/Images/vip_pass.png'),
    ic_camera: require('App/Assets/Images/camera.png'),

    report_camera: require('App/Assets/Images/report_camera.png'),
    report_spam: require('App/Assets/Images/report_spam.png'),
    report_other: require('App/Assets/Images/report_other.png'),

    ic_setting: require('App/Assets/Images/ic_setting.png'),
    ic_location_pin: require('App/Assets/Images/ic_location_pin.png'),
    ic_checkmark: require('App/Assets/Images/ic_checkmark.png'),
}
