export const INITIAL_STATE = {
  profile: {},
  setting:{},
  filters:{},
  photos:{},
  premium:{},
  boost:{},
  luxe:{},
  transterSend:{},
  transterReceive:{},
  gifts:{},
  hangouts:{},
  tasks:{},
  isLoading: false,
  errorMessage: null,
  todayMUsers: [],
};
